---
- name: archive module test
  hosts: all
  tasks:
    - name: Deploying jsp files Create local archive
      archive:
        path: "{{ item }}"
        dest: /tmp/test_archieve.zip
        format: zip
      with_items:
       - 'playbooks/test_arch'
