---
- name: archive module test
  hosts: all
  tasks:
    - name: Deploying jsp files Create local archive
      archive:
        path: "{{ playbook_dir | dirname }}/{{ item }}"
        dest: /tmp/test_archieve.zip
        format: zip
      with_items:
       - 'playbooks/test_arch'
    - name: list /runner/project
      ansible.builtin.find:
        paths: "{{ playbook_dir | dirname }}"
        recurse: yes
