---
- name: archive module test
  hosts: all
  tasks:
      - name: Install git
        ansible.builtin.package:
            name: git
            state: present
      - name: Create temporary archive directory
        ansible.builtin.tempfile:
            state: directory
            suffix: archive
        register: temparchive

      - name: Print return information from the previous task
        ansible.builtin.debug:
            msg: "Temp archive: {{ temparchive.path }}"

      - name: Clone your repository
        git:
            repo: https://github.com/matt8754/ansible-tower-samples.git
            dest: "{{ temparchive.path }}"

      - name: Deploying jsp files Create local archive
        archive:
            path: "{{ item }}"
            dest: /tmp/test_archieve.zip
            format: zip
        with_items:
            - "{{ temparchive.path }}/ansible-tower-samples/playbooks/test_arch"
